class ser(object):
  async def getall(HELP_COMMANDS, HELP_COMMANDU, HELP_COMMANDA, HELP_COMMANDO, HELP_COMMANDAST):
   self.HC=HELP_COMMANDS
   self.HU=HELP_COMMANDU
   self.HA=HELP_COMMANDA
   self.HO=HELP_COMMANDO
   self.HAT=HELP_COMMANDAST
