class ser(object):
  global HC,HU,HA,HO,HAT
  async def getall(HELP_COMMANDS, HELP_COMMANDU, HELP_COMMANDA, HELP_COMMANDO, HELP_COMMANDAST):
   HC=HELP_COMMANDS
   HU=HELP_COMMANDU
   HA=HELP_COMMANDA
   HO=HELP_COMMANDO
   HAT=HELP_COMMANDAST
